name: Deploy to S3
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
        - name: Install dependencies
          run: npm ci
        - name: Gulp runner
          run: npx gulp
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.IAM_ROLE }}
            aws-region: us-east-1
        - name: Deploy to S3
          run: aws s3 sync dist s3://catholicrecords.americanancestors.org --acl public-read --delete
                
